categories:
  supi.ga:
    label: Google Analytics tracker

settings:
  supseven.supi.ga.cookies:
    label: 'Cookies'
    description: 'Names of cookies of Google Analytics'
    type: string
    category: supi.ga
    default: '_ga, _gid, _gat, AMP_TOKEN, _ga_XXX, _gac_XXX, _gac_gb_XXX'
  supseven.supi.ga.id:
    label: 'ID'
    description: 'Google Analytics ID'
    type: string
    category: supi.ga
    default: ''
