services:
  _defaults:
    autowire: true
    autoconfigure: true

  Supseven\Supi\DataProcessing\:
    resource: '../Classes/DataProcessing/*'
    public: true

  Supseven\Supi\ContentObject\SupiJsContentObject:
    public: true
    tags:
      - name: frontend.contentobject
        identifier: 'SUPI_JS'

  Supseven\Supi\CSP\SupiPolicyExtender:
    public: true
    shared: true
    arguments:
      $cache: '@cache.hash'
    tags:
      - name: event.listener
        identifier: 'supseven/supi/csp'
